### ISSUE TITLE
Problem to create man page

### ISSUE THREAD

**Issue by phls** [kytos/python-openflow#538] opened 2018-11-27 18:10 UTC
Hi,

In docs/ when I run "make man" I have this problem:

sphinx-build -b man -d _build/doctrees -W . _build/man
Running Sphinx v1.7.9

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/sphinx/config.py", line 161, in __init__
execfile_(filename, config)
File "/usr/lib/python3/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
exec_(code, _globals)
File "conf.py", line 18, in <module>
import kytos_sphinx_theme
ModuleNotFoundError: No module named 'kytos_sphinx_theme'

make: *** [Makefile:192: man] Error 2

**Comment by viniarck** [comment] 2018-11-28 00:50
Hi @phls,

Looks like you don't have `kytos_sphinx_theme` installed. Could you please follow these steps? I just confirmed the latest commit on master (0a04446) is working as expected:

1 - Make sure you're using Python 3.6:

```
❯ which python
/tmp/python-openflow/.direnv/python-3.6.6/bin/python

```

2 - pip install requirements (at this moment I already have my virtualenv activated)

```
cd python-openflow
pip install -r requirements/dev.txt -U
```

3 - You should see that `kythos_sphinx_theme` is being fetched and installed, for example:

```
Obtaining file:///tmp/python-openflow (from -r requirements/dev.txt (line 8))
Obtaining kytos-sphinx-theme from git+git://github.com/kytos/sphinx-theme.git#egg=kytos-sphinx-theme (from -r requirements/dev.txt (line 7))
  Cloning git://github.com/kytos/sphinx-theme.git to ./.direnv/python-3.6.6/src/kytos-sphinx-theme
Collecting alabaster==0.7.10 (from -r requirements/dev.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/2e/c3/9b7dcd8548cf2c00531763ba154e524af575e8f36701bacfe5bcadc67440/alabaster-0.7.10-py2.py3-none-any.whl
...
```

4 - Double check with `pip freeze | grep theme` to make sure `kytos_sphinx_theme` got installed:

```
pip freeze | grep theme
```

You should see an output similar to this:

```
-e git://github.com/kytos/sphinx-theme.git@ceb2cb36d377d3cd7b509c2ece27a776c0d5c326#egg=kytos_sphinx_theme
sphinx-bootstrap-theme==0.4.14
sphinx-rtd-theme==0.2.4
```

5 - cd to the docs dir and `make`:

```
❯ cd docs

❯ make
make clean
make[1]: Entering directory '/tmp/python-openflow/docs'
rm -rf pyof.*
rm -rf _build/*
make[1]: Leaving directory '/tmp/python-openflow/docs'
make dirhtml
make[1]: Entering directory '/tmp/python-openflow/docs'
sphinx-apidoc -o . ../pyof/ -d10 -M -T
Creating file ./pyof.rst.
Creating file ./pyof.foundation.rst.
Creating file ./pyof.v0x01.rst.
Creating file ./pyof.v0x01.asynchronous.rst.
Creating file ./pyof.v0x01.common.rst.
Creating file ./pyof.v0x01.controller2switch.rst.
Creating file ./pyof.v0x01.symmetric.rst.
Creating file ./pyof.v0x04.rst.
Creating file ./pyof.v0x04.asynchronous.rst.
Creating file ./pyof.v0x04.common.rst.
Creating file ./pyof.v0x04.controller2switch.rst.
Creating file ./pyof.v0x04.symmetric.rst.
sed -i "/Submodules/,+1d" *.rst
sed -i "/Subpackages/,+1d" *.rst
sphinx-build -b dirhtml -d _build/doctrees  -W . _build/dirhtml
Running Sphinx v1.5.6
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.kytos.io/kytos/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [dirhtml]: targets for 19 source files that are out of date
updating environment: 19 added, 0 changed, 0 removed
reading sources... [100%] references
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] references
generating indices... genindex py-modindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

Build finished. The HTML pages are in _build/dirhtml.
make[1]: Leaving directory '/tmp/python-openflow/docs'

❯ make man
sphinx-build -b man -d _build/doctrees  -W . _build/man
Running Sphinx v1.5.6
making output directory...
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
writing... python-openflowlibrary.1 { index examples/index pyof pyof.foundation pyof.v0x01 pyof.v0x01.asynchronous pyof.v0x01.common pyof.v0x01.controller2switch pyof.v0x01.symmetric p
yof.v0x04 pyof.v0x04.asynchronous pyof.v0x04.common pyof.v0x04.controller2switch pyof.v0x04.symmetric AUTHORS LICENSE }
build succeeded.

Build finished. The manual pages are in _build/man.
```

**Comment by phls** [comment] 2018-11-28 12:03
Hi @viniarck thanks.

I will have to package it.

@beraldoleal could you release sphinx-theme?

**Comment by beraldoleal** [comment] 2018-11-28 12:05
Our sphinx theme is here [1]. But I'm not sure if this should be on debian. Or if we could think on something different. 

[1] - https://github.com/kytos/sphinx-theme

**Comment by phls** [comment] 2018-11-28 15:06
@beraldoleal do you know when you will decide about package it or not?

**Comment by beraldoleal** [comment] 2018-11-28 15:08
This is up to you. What I mean was:I'm not sure about the debian policy to have a specific sphinx theme on debian repository". I'm not sure if this is normal or not.

**Comment by phls** [comment] 2018-11-28 15:11
Ah ok. Let's try. Could release it?

**Comment by beraldoleal** [comment] 2018-11-28 15:13
done.

**Comment by hdiogenes** [comment] 2020-12-30 20:02
As per the comment above, kytos-sphinx-theme was released as a separate package that's included in the dev requirements, so the man page build works as expected.

**Closed by hdiogenes** 2020-12-30 20:02 UTC
